name: Code style

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
     fail-fast: true
     matrix:
       php: [8.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@latest
        with:
          verboseMode: true
          configPath: ./pint.json
          onlyDirty: true

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fixes coding style"
